### ISSUE TITLE
Eliminate deprecated CONSTANTS

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/clock#5]
This package still uses deprecated Dart 1 SCREAMING CAPS CONSTANTS.  These will be removed shortly in Dart 2.  This rewriting tool is available for the migration: This tool is available for the migration: https://github.com/dart-lang/dart2_fix .

**Comment by natebosch** [comment]
Looks like this was fixed in https://github.com/dart-lang/clock/commit/e3dd2f234ba2c16a251ed644ac457cde7aec9eeb
